RAC-409 fix: 메인 프로필 카드 디자인 변경
WE-ARE-RACCOONS/postgraduate-front pull request #283
Opened 2024-07-22 00:38 UTC by yeonsuu21

## 🦝 PR 요약
메인 프로필 카드 디자인 변경
## ✨ PR 상세 내용
메인 프로필 카드 디자인 변경
## 🚨 주의 사항
🔗 피그마에서 디자인을 못찾아서 노션에 있는거 최대한 비슷하게 작업 했습니다..! 제가 볼때는 크..게 튀는건 없는것같습니다!
## 📸 스크린샷
<img width="391" alt="스크린샷 2024-07-22 오전 9 27 29" src="https://github.com/user-attachments/assets/b701bd4a-4f69-4ca5-ac27-241522ee70e2">
<img width="380" alt="스크린샷 2024-07-22 오전 9 27 39" src="https://github.com/user-attachments/assets/2edd39e9-b438-43c1-bff0-88d3d21868d7">

## ✅ 체크 리스트

- [ ] 리뷰어 설정했나요?
- [ ] Label 설정했나요?
- [ ] 제목 양식 맞췄나요? (ex. RAC-1 feat: 기능 추가)
- [ ] 변경 사항에 대한 테스트 진행했나요?
- [ ] `npm run format:fix` 실행했나요?

2024-07-22 04:09 UTC, leehyewon0531 requested changes
![image](https://github.com/user-attachments/assets/b127695a-b462-472c-9dec-2a9c101f620f)

좋긴 한데 피그마 디자인과 디테일이 조금 다른 것 같습니다!! 그리고 `>` 화살표 추가하기로 했는데 그 부분이 안 되어 있는 것 같습니다! 피그마 해당 부분 제가 코멘트로 태그해드릴게여!!

2024-08-04 07:15 UTC, leehyewon0531 reviewed
수고 많으셨습니다!!! 🙇🙇🙇

2024-08-04 07:15 UTC, leehyewon0531 commented on public/right-arrow.png
요거 기존에 있는 arrow-right랑 이름 겹쳐서 이렇게 하신 걸까요?! 근데 연하고/진하고의 차이가 있어서 arrow-right-bold 이런 식으로 차이를 주는 게 더 직관적이지 않을까 싶습니다!!

2024-08-04 07:15 UTC, leehyewon0531 commented on src/components/SeniorProfile/SeniorProfile.tsx
> +              {data.postgradu ? `[${data.postgradu.replace('학교', '')}]` : ''}&nbsp;
굿굿 😍

2024-08-04 13:44 UTC, yeonsuu21 commented on public/right-arrow.png
오 네넵 !!! 변경했습니다앙 !!

2024-08-04 13:48 UTC, merged